image: docker:19.03.1

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_DRIVER: overlay2

services:
  - docker:19.03.1-dind

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -t docker.io/vekservicos/flutter-android:$CI_COMMIT_REF_NAME .
    - docker push docker.io/vekservicos/flutter-android:$CI_COMMIT_REF_NAME
